sudo: required

language: php

php:
  - '7.1'

services:
  - docker

before_install:
  - docker pull ibejohn818/php:php71w-build
  - docker run --rm -it -v $(pwd):/code -w /code ibejohn818/php:php71w-build  /bin/bash -c '/usr/bin/composer update && /usr/bin/composer install'

script:
  - docker run --rm -it -v $(pwd):/code -w /code ibejohn818/php:php71w-build /bin/bash -c 'vendor/bin/phpunit tests --coverage-clover=clover.xml'

after_success:
  - bash <(curl -s https://codecov.io/bash)
