<?php

$providers = [
    'Google'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
            [
                'help'=>'',
                'key'=>'clientId',
                'default'=>'',
                'type'=>'string'
            ],
            [
                'help'=>'',
                'key'=>'clientSecret',
                'default'=>'',
                'type'=>'string'
            ],
            [
                'help'=>'Permission scopes separated each separated by a space',
                'key'=>'clientScopes',
                'default'=>'email profile',
                'type'=>'string'
            ],
        ]
    ],
    'Github'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
            [
                'help'=>'',
                'key'=>'clientId',
                'default'=>'',
                'type'=>'string'
            ],
            [
                'help'=>'',
                'key'=>'clientSecret',
                'default'=>'',
                'type'=>'string'
            ],
            [
                'help'=>'',
                'key'=>'apiScopes',
                'default'=>'user:email',
                'type'=>'string'
            ],
            [
                'help'=>'',
                'key'=>'cacheConfig',
                'default'=>'default',
                'type'=>'string'
            ],
        ]
    ],
    'Facebook'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
        ]
    ],
    'Linkedin'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
        ]
    ],
    'Yahoo'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
        ]
    ],
    'Bitbucket'=>[
        'help'=>'',
        'settings'=>[
            [
                'help'=>'',
                'key'=>'enabled',
                'default'=>false,
                'type'=>'bool'
            ],
        ]
    ],
];

return $providers;
